"""Change column data type

Revision ID: e59692d6bdd5
Revises: dd8475a6470f
Create Date: 2023-05-18 10:39:03.262500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59692d6bdd5'
down_revision = 'dd8475a6470f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.add_column('usertable', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('usertable', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('usertable', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertable', 'last_login')
    op.drop_column('usertable', 'create_time')
    op.drop_column('usertable', 'birthday')
    op.drop_column('usertable', 'password')
    # ### end Alembic commands ###
